### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by InsaneJ** [Parzivail-Modding-Team/LightLevel#2]
Using LightLevel 1.1.0 and Fabric Loader 0.8.2 I get the following crash:

> [20:14:42] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lightlevel requires {fabric @ [*]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:169) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:602) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:179) ~[fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:169) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.8.2+build.194.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:167) ~[fabric-loader-0.8.2+build.194.jar:?]
	... 13 more

Log:
https://paste2.org/NhUtOK2v

**Comment by parzivail** [comment]
You also need to install [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api).
